#include <stdio.h>                                                                                                                                                                                          
                                                                                                                                                                                                            
int main(void){                                                                                                                                                                                             
  int n, i, right=0, left=0;                                                                                                                                                                                
  char s[100];                                                                                                                                                                                              
  scanf("%d", &n);                                                                                                                                                                                          
  scanf("%s", s);                                                                                                                                                                                           
  for(i=0; i<n; ++i){                                                                                                                                                                                       
    if(s[i] == '('){                                                                                                                                                                                        
      left += 1;                                                                                                                                                                                            
    } else if(s[i] == ')' && left > 0 ){                                                                                                                                                                    
      left -= 1;                                                                                                                                                                                            
    }else{                                                                                                                                                                                                  
      right += 1;                                                                                                                                                                                           
    }                                                                                                                                                                                                       
  }                                                                                                                                                                                                         
  for(i=0; i<right; ++i){                                                                                                                                                                                   
    printf("(");                                                                                                                                                                                            
  }                                                                                                                                                                                                         
  printf("%s", s);                                                                                                                                                                                          
  for(i=0; i<left; ++i){                                                                                                                                                                                    
    printf(")");                                                                                                                                                                                            
  }                                                                                                                                                                                                         
  return 0;                                                                                                                                                                                                 
} 